version: '3.9'

volumes:
  sub-postgres-data:
  sub-static-data:

services:
  web:
    container_name: subtitler-api-release
    restart: unless-stopped
    volumes:
      - sub-static-data:/src/vol/web
    build:
      context: ./src
      args:
        REQUIREMENTS_FILE: dev-requirements.txt
    env_file:
      - .env
    depends_on:
        - postgres

  postgres:
    container_name: subtitler-database-release
    restart: unless-stopped
    image: postgres:14.6-alpine
    env_file:
      - .env
    volumes:
      - sub-postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432

  proxy:
    container_name: subtitler-proxy-release
    build:
      context: ./proxy
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "8002:8000"
    volumes:
      - sub-static-data:/vol/static