version: '3.9'

volumes:
  postgres-data:

services:
  web:
    container_name: subtitler-api-dev
    restart: unless-stopped
    build:
      context: ./src
      args:
        REQUIREMENTS_FILE: dev-requirements.txt
    ports:
        - "8000:8000"
    env_file:
      - .env
    depends_on:
        - postgres

  postgres:
    container_name: subtitler-database-dev
    restart: unless-stopped
    image: postgres:14.6-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432