# Generated by Django 4.1.7 on 2023-03-31 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=30)),
                ("is_film_genre", models.BooleanField(default=False)),
                ("is_series_genre", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("other_titles", models.JSONField(blank=True, null=True)),
                ("released", models.PositiveIntegerField(blank=True)),
                ("ended", models.PositiveIntegerField(blank=True)),
                ("number_of_seasons", models.PositiveIntegerField(blank=True)),
                ("number_of_episodes", models.PositiveIntegerField(blank=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginners"),
                            ("beginner_intermediate", "Beginner - Intermediate"),
                            ("intermediate", "Intermediate"),
                            ("intermediate_advanced", "Intermediate - Advanced"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=30,
                    ),
                ),
                ("poster", models.ImageField(blank=True, null=True, upload_to="")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("genres", models.ManyToManyField(related_name="series", to="subtitles.genre")),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("season_number", models.PositiveIntegerField(blank=True)),
                ("number_of_episodes", models.PositiveIntegerField(blank=True)),
                ("released", models.PositiveIntegerField(blank=True)),
                ("ended", models.PositiveIntegerField(blank=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="seasons", to="subtitles.series"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("other_titles", models.JSONField(blank=True, null=True)),
                ("released", models.PositiveIntegerField(blank=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginners"),
                            ("beginner_intermediate", "Beginner - Intermediate"),
                            ("intermediate", "Intermediate"),
                            ("intermediate_advanced", "Intermediate - Advanced"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=30,
                    ),
                ),
                ("poster", models.ImageField(blank=True, null=True, upload_to="")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("summary", models.CharField(blank=True, max_length=1023)),
                ("idioms", models.JSONField(blank=True, null=True)),
                ("difficult_phrases", models.JSONField(blank=True, null=True)),
                ("uncommon_words", models.JSONField(blank=True, null=True)),
                ("words_count", models.JSONField(blank=True, null=True)),
                ("questions", models.JSONField(blank=True, null=True)),
                ("genres", models.ManyToManyField(related_name="films", to="subtitles.genre")),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("episode_number", models.PositiveIntegerField(blank=True)),
                ("episode_title", models.CharField(blank=True, max_length=255)),
                ("other_titles", models.JSONField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("summary", models.CharField(blank=True, max_length=1023)),
                ("idioms", models.JSONField(blank=True, null=True)),
                ("difficult_phrases", models.JSONField(blank=True, null=True)),
                ("uncommon_words", models.JSONField(blank=True, null=True)),
                ("words_count", models.JSONField(blank=True, null=True)),
                ("questions", models.JSONField(blank=True, null=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="episodes", to="subtitles.season"
                    ),
                ),
            ],
        ),
    ]
