# Generated by Django 4.1.7 on 2023-04-06 11:40

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subtitles", "0002_remove_season_number_of_episodes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilmWordQuantity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=0)),
                (
                    "film",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="subtitles.film"
                    ),
                ),
                ("word", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subtitles.word")),
            ],
        ),
        migrations.AlterField(
            model_name="word",
            name="film",
            field=models.ManyToManyField(
                blank=True, related_name="words", through="subtitles.FilmWordQuantity", to="subtitles.film"
            ),
        ),
    ]
