# Generated by Django 4.1.7 on 2023-04-06 11:42

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subtitles", "0003_filmwordquantity_alter_word_film"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeWordQuantity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=0)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="subtitles.episode"
                    ),
                ),
                ("word", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subtitles.word")),
            ],
        ),
        migrations.DeleteModel(
            name="WordQuantity",
        ),
        migrations.AlterField(
            model_name="word",
            name="episode",
            field=models.ManyToManyField(
                blank=True, related_name="words", through="subtitles.EpisodeWordQuantity", to="subtitles.episode"
            ),
        ),
    ]
