# Generated by Django 4.1.7 on 2023-04-10 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subtitles", "0005_episodequestion_filmquestion_delete_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name_plural": "series"},
        ),
    ]
