# Generated by Django 4.2 on 2023-04-25 17:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("subtitles", "0006_alter_series_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodequestion",
            name="question_text",
        ),
        migrations.RemoveField(
            model_name="filmquestion",
            name="question_text",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="text",
        ),
        migrations.AlterField(
            model_name="episode",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="episodequestion",
            name="answer_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="filmquestion",
            name="answer_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="definition",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="definition",
            field=models.TextField(blank=True),
        ),
    ]
