# Generated by Django 4.2 on 2023-04-26 18:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("subtitles", "0007_remove_episodequestion_question_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodequestion",
            name="question_text",
            field=models.TextField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filmquestion",
            name="question_text",
            field=models.TextField(default="111"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phrase",
            name="text",
            field=models.TextField(default="111"),
            preserve_default=False,
        ),
    ]
