# Generated by Django 4.2 on 2023-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subtitles", "0008_episodequestion_question_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="genres",
            field=models.ManyToManyField(blank=True, null=True, related_name="films", to="subtitles.genre"),
        ),
        migrations.AlterField(
            model_name="film",
            name="released",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
