# Generated by Django 4.2 on 2023-05-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subtitles", "0008_episodequestion_question_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="released",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
