# Generated by Django 4.2 on 2023-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subtitles", "0009_alter_film_released"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode",
            options={"ordering": ["season", "episode_number"]},
        ),
        migrations.AlterModelOptions(
            name="episodequestion",
            options={"ordering": ["episode", "question_text"]},
        ),
        migrations.AlterModelOptions(
            name="episodewordquantity",
            options={"ordering": ["episode", "word"]},
        ),
        migrations.AlterModelOptions(
            name="film",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="filmquestion",
            options={"ordering": ["film", "question_text"]},
        ),
        migrations.AlterModelOptions(
            name="filmwordquantity",
            options={"ordering": ["film", "word"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="phrase",
            options={"ordering": ["text"]},
        ),
        migrations.AlterModelOptions(
            name="season",
            options={"ordering": ["series", "season_number"]},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ["title"], "verbose_name_plural": "Series"},
        ),
        migrations.AlterModelOptions(
            name="word",
            options={"ordering": ["text"]},
        ),
        migrations.AlterField(
            model_name="genre",
            name="title",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
